((c-mode . ((c-file-style . "linux")
            (indent-tabs-mode . nil)
            (show-trailing-whitespace . t)
            (c-basic-offset . 4)
            (tab-width . 4)
            ))
 (vala-mode . ((indent-tabs-mode . nil)
               (show-trailing-whitespace . t)
               (c-basic-offset . 4)
               (tab-width . 4)
               ))
 )
