/* mconn-crypt.vapi generated by vapigen, do not modify. */

namespace MConn {
	[CCode (cheader_filename = "mconn-crypt.h", ref_function="mconn_crypt_ref", unref_function = "mconn_crypt_unref")]
	[Compact]
	public class Crypt {
		public unowned GLib.Bytes decrypt (GLib.Bytes data) throws GLib.Error;
		[CCode (has_construct_function = false)]
		public Crypt.for_key_path (string path);
		public unowned string get_public_key_pem ();
	}
}
